language: python
python:
  - "3.5"
  - "3.6"
  - "nightly" 
# command to install dependencies
install: "pip install -r req.txt"
# command to run tests
script: "coverage run L3HW/Roadmap.ipynb"
after_success:
  - coveralls
