# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(default='in_progress', max_length=100),
        ),
    ]
