# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
