# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hw5', '0002_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
